### ISSUE TITLE
Add docs from OpenHands' feedback

### ISSUE THREAD

**Issue by ftnext** [ftnext/sphinx-revealjs-copycode#2]
https://app.all-hands.dev/conversations/85c5de9152234660ad0f15ef9fcf76fc

>sphinx-revealjs と一緒に使う https://github.com/ftnext/sphinx-revealjs-copycode を試しに使ってみてください。 うまくいったところ、いかなかったことを知って、最終的にはドキュメントの修正につなげたいです

---

# sphinx-revealjs-copycode テスト結果

sphinx-revealjs-copycode 拡張機能を sphinx-revealjs と一緒に使用してテストした結果をご報告します。

## うまくいったこと

1. **インストールと設定**:
   - GitHub からの拡張機能のインストールは問題なく完了
   - `conf.py` への拡張機能の追加は簡単（README の通り1行追加するだけ）
   - 拡張機能が自動的に copycode.js プラグインをダウンロード

2. **機能性**:
   - すべてのコードブロックにコピーボタンが表示される
   - 様々な言語（Python, JavaScript, HTML, CSS, Bash）のコードブロックで動作
   - 標準の `code-block` と `revealjs-code-block` の両方で機能
   - クリック時にコードがクリップボードにコピーされる

3. **視覚的フィードバック**:
   - ボタンをクリックすると色が変わる（オレンジから緑へ）
   - コピー完了後、自動的に元の状態に戻る

## 改善できる点

1. **ドキュメント**:
   - README が非常に最小限で、すべての機能を説明していない
   - `:data-id:` 属性の目的や使用方法が説明されていない
   - カスタマイズオプションのドキュメントがない

2. **視覚的フィードバック**:
   - 色の変化が一部のユーザーには分かりにくい可能性がある
   - コピー成功時のフィードバックがもう少し明確だと良い

3. **アクセシビリティ**:
   - アクセシビリティ機能に関する明確なドキュメントがない

## ドキュメント改善の提案

1. README を拡張して、より詳細な使用方法を含める
2. `:data-id:` 属性の目的と使用方法を説明する
3. 利用可能なカスタマイズオプション（色、ボタンテキストなど）を文書化する
4. 異なるコードブロックタイプとその動作の例を提供する
5. アクセシビリティ機能に関する情報を追加する
6. 一般的な問題のトラブルシューティング情報を含める
7. 拡張機能の動作を示すスクリーンショットやGIFを追加する

## 技術的詳細

拡張機能は内部的に [Reveal.js-copycode](https://github.com/Martinomagnifico/reveal.js-copycode/) プラグイン（v1.2.0）を使用しています。このプラグインは以下のファイルを含みます：

- `copycode.js` - メインのJavaScriptファイル
- `copycode.css` - スタイル定義
- `copycode.esm.js` - ES モジュール版

CSS では、コピーボタンのスタイルをカスタマイズするための CSS 変数が定義されています：

```css
:root {
  --cc-copy-bg: orange;       /* コピーボタンの背景色 */
  --cc-copied-bg: green;      /* コピー後のボタン背景色 */
  --cc-copy-color: black;     /* コピーボタンのテキスト色 */
  --cc-copied-color: white;   /* コピー後のボタンテキスト色 */
  /* その他のカスタマイズ変数 */
}
```

## 結論

sphinx-revealjs-copycode 拡張機能は基本的な機能は問題なく動作し、プレゼンテーション内のコードブロックからコードをコピーする機能を提供します。ただし、ドキュメントが最小限であるため、すべての機能やカスタマイズオプションを理解するのが難しい状況です。

ドキュメントを改善することで、ユーザーがこの拡張機能をより効果的に活用できるようになるでしょう。特に、`:data-id:` 属性の目的や、ボタンの外観や動作をカスタマイズする方法についての説明が役立つと思われます。
